"""empty message

Revision ID: 5e68b4cb55c0
Revises: 
Create Date: 2025-07-17 22:24:56.250992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e68b4cb55c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('categories', sa.Enum('primer_plato', 'segundo_plato', 'postres', 'bebidas', name='estadocategorias'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('camarero', 'cocinero', 'admin', name='estadorol'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('disponible', 'ocupada', 'reservada', 'cerrada', name='estadomesa'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('pendiente', 'en_cocina', 'ready', 'cancelada', name='estadocomanda'), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=True),
    sa.Column('guest_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_plates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('count_plat', sa.Integer(), nullable=True),
    sa.Column('status_plate', sa.Enum('pending', 'completed', 'rejected', name='estadoplato'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plate_id'], ['plates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_plates')
    op.drop_table('orders')
    op.drop_table('tables')
    op.drop_table('user')
    op.drop_table('plates')
    # ### end Alembic commands ###
